### ISSUE TITLE
Match live score not working

### ISSUE THREAD

**Issue by Chefski** [axsddlr/vlrggapi#10]
https://vlrggapi.vercel.app/match/live_score is not working. It's returning:
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED

**Comment by axsddlr** [comment]
fixed here: https://github.com/axsddlr/vlrggapi/commit/720a0bc343e08af4f79da72ca5e547fb62990c85

Be aware of new values in json output due to vlr.gg handling of ct and t side scores. They end up swapping base on mid-round change. Code accounts for it
