### ISSUE TITLE
`/news` returning Error: response status is 500

### ISSUE THREAD

**Issue by Chefski** [axsddlr/vlrggapi#13]
<img width="1436" alt="image" src="https://github.com/axsddlr/vlrggapi/assets/100310118/91f0355c-b3d0-4e9c-879f-b0fbf1b42bd4">

**Comment by axsddlr** [comment]
https://github.com/axsddlr/vlrggapi/commit/ee9283031fe839bcdaae4c71eb88fd699e87657d
