### ISSUE TITLE
statistic players information not good

### ISSUE THREAD

**Issue by fraecar** [axsddlr/vlrggapi#14]
Hello, I wanted the statistics players of Europe but when I check the information, that was not good because vlr.gg add a new column (rating) and that's not be change since 2022 in the repository github
![image](https://github.com/axsddlr/vlrggapi/assets/76265248/648031bd-c28f-45c1-af4a-5dddb4de0b67)
I propose this to change this
**before :**
            
           `color_sq = [stats.text() for stats in item.css("td.mod-color-sq")]
            acs = color_sq[0]
            kd = color_sq[1]
            kast = color_sq[2]
            adr = color_sq[3]
            kpr = color_sq[4]
            apr = color_sq[5]
            fkpr = color_sq[6]
            fdpr = color_sq[7]
            hs = color_sq[8]
            cl = color_sq[9]

            result.append(
                {
                    "player": player_name,
                    "org": org,
                    "average_combat_score": acs,
                    "kill_deaths": kd,
                    "kill_assists_survived_traded": kast,
                    "average_damage_per_round": adr,
                    "kills_per_round": kpr,
                    "assists_per_round": apr,
                    "first_kills_per_round": fkpr,
                    "first_deaths_per_round": fdpr,
                    "headshot_percentage": hs,
                    "clutch_success_percentage": cl,
                }
            )`

**after :**

          ` color_sq = [stats.text() for stats in item.css("td.mod-color-sq")]
            rat = color_sq[0]
            acs = color_sq[1]
            kd = color_sq[2]
            kast = color_sq[3]
            adr = color_sq[4]
            kpr = color_sq[5]
            apr = color_sq[6]
            fkpr = color_sq[7]
            fdpr = color_sq[8]
            hs = color_sq[9]
            cl = color_sq[10]

            result.append(
                {
                    "player": player_name,
                    "org": org,
                    "rating": rat,
                    "average_combat_score": acs,
                    "kill_deaths": kd,
                    "kill_assists_survived_traded": kast,
                    "average_damage_per_round": adr,
                    "kills_per_round": kpr,
                    "assists_per_round": apr,
                    "first_kills_per_round": fkpr,
                    "first_deaths_per_round": fdpr,
                    "headshot_percentage": hs,
                    "clutch_success_percentage": cl,
                }
            )`

**Comment by axsddlr** [comment]
https://github.com/axsddlr/vlrggapi/commit/bd9bbb0f03e59331262df8f4b6ab1f19c7e541e5
