### ISSUE TITLE
maps and Elo

### ISSUE THREAD

**Issue by scarlemange** [axsddlr/vlrggapi#20]
i need the maps and Elo of teams in the ( https://vlrggapi.vercel.app/match?q=results)
can you make it for me ?

**Comment by axsddlr** [comment]
that endpoint basically scrapes surface info from: https://www.vlr.gg/matches/results

to achieve that I would have to scrape the match detail page and get the data from there. Better implement would be a new endpoint that give match_result_details

**Comment by scarlemange** [comment]
How can i do that?
I'm currently making an data analysis program that predict the matches base on elo, maps, last games and players.
