### ISSUE TITLE
Unable to pull LATAM/South American data

### ISSUE THREAD

**Issue by Dabby-Tabby** [axsddlr/vlrggapi#39]
### Describe the bug

I.e. take https://vlrggapi.vercel.app/stats/sa/30, returns {   "data": {     "status": 200,     "segments": []   } }. 

### Steps to reproduce

https://vlrggapi.vercel.app/#/default/VLR_stats_stats__region___timespan__get

### Expected behavior

Should display the data for the region

### Actual behavior

Displays nothing

**Comment by SleepingStar** [comment]
bump

**Comment by axsddlr** [comment]
fix the inherit issue with this query. I may have to redo how vlr_stats are scrapped but for now i did this:

https://github.com/axsddlr/vlrggapi/commit/0e5dcd38edc4a3e074f0cb90caf8e6ccdad1cfa4

should allow you to use all for any region to get all tight stats
