### ISSUE TITLE
Player Stats

### ISSUE THREAD

**Issue by ecjz01** [axsddlr/vlrggapi#4]
Hi, I noticed an issue when getting the player stats, the values are corresponding to the incorrect title and that the clutch success% is missing, when comparing the values 
from the response and on vlr.
![image](https://user-images.githubusercontent.com/47509193/168161682-9d753ebc-77e1-4d24-82bc-477dba6f7a0e.png)
![vlr](https://user-images.githubusercontent.com/47509193/168161963-22af4930-384f-4aa9-85cb-854c88edac1c.png)

**Comment by axsddlr** [comment]
will take a look when i have time

**Comment by axsddlr** [comment]
> Hi, I noticed an issue when getting the player stats, the values are corresponding to the incorrect title and that the clutch success% is missing, when comparing the values from the response and on vlr. ![image](https://user-images.githubusercontent.com/47509193/168161682-9d753ebc-77e1-4d24-82bc-477dba6f7a0e.png) ![vlr](https://user-images.githubusercontent.com/47509193/168161963-22af4930-384f-4aa9-85cb-854c88edac1c.png)

youre comparing stats from a limited timespawn, however my code looks at the ytd timespan thats why the stats are different, ill will adjust the endpoint to allow user to check timespan as well

**Comment by ecjz01** [comment]
That sounds great but also taking the values of the stats into consideration it seems like the order isn't correct as "195.6" killed per round and an average damage per round of "77%" doesn't make sense.

**Comment by axsddlr** [comment]
> That sounds great but also taking the values of the stats into consideration it seems like the order isn't correct as "195.6" killed per round and an average damage per round of "77%" doesn't make sense.

APR and KPR is measured in VLR's stats, all im doing is scraping the values from their table. also https://github.com/axsddlr/vlrggapi/commit/a840a017a8acac589d106956a6fcd6032b4a2d4a

**Comment by ecjz01** [comment]
Sorry to continue bothering you, but I believe that between the kd and adr, you're missing kast. Which is causing all the values past kd to be under what looks like the wrong header.
https://github.com/axsddlr/vlrggapi/blob/c132a8bf26038304a6b741f2af22751f5d89d108/api/scrape.py#L247

**Comment by axsddlr** [comment]
https://github.com/axsddlr/vlrggapi/commit/7dcdd77cb0eaea1098f472ee6aa2016f68b4c5f3

**Comment by axsddlr** [comment]
https://vlrggapi.vercel.app/ new api location.
